In [1]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import numpy as np

In [2]:
from sklearn.datasets import load_digits
digits=load_digits()

In [3]:
X=digits.data
y=digits.target

In [4]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=3)

In [5]:
from sklearn.model_selection import cross_val_score

In [7]:
cross_val_score(LogisticRegression(max_iter=200),X,y,cv=kf)

array([0.91986644, 0.94156928, 0.91652755])

In [10]:
cross_val_score(SVC(),X,y,cv=kf)

array([0.96494157, 0.97996661, 0.96494157])

In [9]:
cross_val_score(RandomForestClassifier(),X,y,cv=kf)

array([0.94323873, 0.95826377, 0.92821369])